export const FORGOT_PASSWORD = "/api/auth/forgot-password"
export const RESET_PASSWORD = "/api/auth/reset-password"
export const LOGIN = "/api/auth/login"
export const REGISTER = "/api/auth/register"
export const CONFIRM_EMAIL = "/api/auth/confirm-email"
export const CREATE_POST = "/api/posts"
export const GET_ALL_POSTS = "/api/posts"
