export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const OAUTH_LOGIN_SUCCESS = "OAUTH_LOGIN_SUCCESS"
export const OAUTH_LOGIN_FAILED = "OAUTH_LOGIN_FAILED"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const LOGOUT = "LOGOUT"
export const ADD_POSTS = "ADD_POSTS"
export const EDITED_POST = "EDITED_POST"
export const SET_CURRENT_POST = "SET_CURRENT_POST"
export const ADD_NEWS = "ADD_NEWS"
export const EDITED_NEWS = "EDITED_NEWS"

export const TEST = "TEST"

export const SET_LOADING = "SET_LOADING"